### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by ljharb** [mitsuruog/javascript-style-guide#14]
I don't speak Japanese, but I'm told the following: "コンポネント名 should be コンポーネント名".

**Comment by ljharb** [comment]
Also:

1. for the `Alignment` section, the current translation (`JSX構文の引数はこれらのスタイルに従うこと`) translates to something along the lines of "Parameters for JSX syntax should follow the following styles".  that doesn't sound like alignment to me, so if you want to fix it, you can change `引数` to `位置揃え`.

2. typo in the `Props` section:
アクセシビリティを複雑なものにして `い` まいます。
should be
アクセシビリティを複雑なものにして `し` まいます。

**Comment by mitsuruog** [comment]
sorry for late reply.
all of your suggestions is definitely correct.

oops, maybe I have misread `alignment ` as `arguments`.
