### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by nasikusa** [mitsuruog/javascript-style-guide#30]
* 3.6 : 括っう → 括る
* 3.7 : の関数よ → の関数を
* 7.7 : [7.7 → 7.7
* 10.2 : 10.2が2つ重複してます
* 11.2 : 今のこころ → 今のところ
* 23.6 : 一致さる → 一致させる

上記のところが誤植になっている気がします。
10.2は重複してました。

**Comment by mitsuruog** [comment]
ありがとうございます。
もしお時間あるようでしたら、PRお待ちしています！

**Comment by nasikusa** [comment]
[PR](https://github.com/mitsuruog/javascript-style-guide/pull/31)作りました!
